### Dataset
file_paths:
  train: /storage/agrp/dreyet/FastCaloSim/FastCalNO/data/dataset_2_1.hdf5
  val: /storage/agrp/dreyet/FastCaloSim/FastCalNO/data/dataset_2_2.hdf5
  test: /storage/agrp/dreyet/FastCaloSim/FastCalNO/data/dataset_2_2.hdf5
entry_ranges:
  train: [0, null]
  val: [0, 10000]
  test: [0, null]
particle: electron
binning: /storage/agrp/dreyet/FastCaloSim/FastCalNO/SPL_OFM/configs/binning_dataset_2.xml

dims:
  x: 16
  y: 9
  z: 45


transforms:
  incident_energies:
    type: log
    offset: 0
    norm: 7
    shift: -6.9
  showers:
    type: log
    offset: 1
    norm: 8.5
    shift: 0
  r:
    type: standard
    mean: 20.925
    std: 12.007
  phi:
    type: standard
    mean: 0.000
    std: 17.060
  z:
    type: standard
    mean: 22.000
    std: 13.000

### FNO
modes: 16
vis_channels: 1
hidden_channels: 16
proj_channels: 16

### FM: TODO